import { useState, useRef, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowUp, Sparkles, Compass, MessageSquarePlus } from 'lucide-react';
import { useUser } from '../context/UserContext';
import { sendAdvisorChat, buildAdvicePayload } from '../lib/aiAdvisor';
import { aiAdvisorResponses } from '../data/recommendations';
import { getStudentContext } from '../data/streamConfig';
import { useScrollTop } from '../hooks/useLocalStorage';
import { fetchLatestResult } from '../lib/assessmentResults';
import Logo from '../components/Logo';
import BackLink from '../components/BackLink';

// AI responses are generated by the NAVORA backend via OpenRouter
// (see src/lib/aiAdvisor.js sendAdvisorChat) — no hardcoded/mock replies.
export default function Advisor() {
  useScrollTop();
  const { userType: localUserType, answers: localAnswers, chatHistory, addChatMessage, setChatHistory, user } = useUser();
  const [remoteAnswers, setRemoteAnswers] = useState(null);
  const [remoteUserType, setRemoteUserType] = useState(null);

  // Load Supabase latest result as single source of truth (Dashboard → AI Advisor same context)
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const res = await fetchLatestResult();
      if (cancelled) return;
      if (res?.data?.assessment_data) {
        const a = res.data.assessment_data;
        setRemoteAnswers(a);
        // Derive userType from stored flow if present
        const flow = a.flow || res.data.assessment_type;
        if (flow) {
          if (String(flow).includes('graduation')) setRemoteUserType(flow.includes('parent') ? 'parent' : 'graduate');
          else if (String(flow).includes('class12') || String(flow).includes('class10')) setRemoteUserType(flow.includes('parent') ? 'parent' : flow.includes('graduate') ? 'graduate' : String(flow).replace('student_','').replace('parent_',''));
        }
      }
    })();
    return () => { cancelled = true; };
  }, [user?.email]);

  const userType = remoteUserType || localUserType;
  const answers = remoteAnswers || localAnswers;

  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);
  const textareaRef = useRef(null);

  const context = userType ? getStudentContext(userType, answers) : null;

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [chatHistory, isTyping]);

  // Greeting once for a brand-new chat (persisted chatHistory is the single source of truth)
  useEffect(() => {
    if (chatHistory.length === 0) {
      addChatMessage({
        role: 'assistant',
        content: aiAdvisorResponses.greeting,
        timestamp: new Date(),
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Start a new chat - clears history and shows initial questions
  const startNewChat = () => {
    setChatHistory([]);
  };

  const lastSendRef = useRef(0);
  const handleSend = async (message = input) => {
    const trimmed = String(message || '').trim().slice(0, 500);
    if (!trimmed) return;
    const now = Date.now();
    if (now - lastSendRef.current < 1200) return; // rate-limit (F5)
    if (isTyping) return;
    // Cap total history before adding (F9)
    if (chatHistory.length >= 100) return;
    lastSendRef.current = now;

    addChatMessage({ role: 'user', content: trimmed, timestamp: new Date() });
    setInput('');
    setIsTyping(true);

    // Preserve FULL conversation history + profile on EVERY request (backend is stateless)
    const history = [
      ...chatHistory.map((m) => ({ role: m.role, content: m.content })),
      { role: 'user', content: trimmed },
    ];
    try {
      // Enrich context with resolved profile so chat continues existing flow (profile + history)
      let enriched = context && typeof context === 'object' ? { ...context } : {};
      try {
        const payload = buildAdvicePayload(userType, answers);
        if (payload?.resolvedProfile) enriched = { ...enriched, resolvedProfile: payload.resolvedProfile };
        if (!enriched.stageLabel && payload?.summary?.stageLabel) enriched.stageLabel = payload.summary.stageLabel;
        if (!enriched.stream && payload?.summary?.streamLabel) enriched.stream = { label: payload.summary.streamLabel };
        if (!enriched.selections?.length && payload?.summary?.selections?.length) enriched.selections = payload.summary.selections;
      } catch {}
      const data = await sendAdvisorChat(history, userType, enriched);
      addChatMessage({ role: 'assistant', content: data.content, timestamp: new Date() });
    } catch (err) {
      addChatMessage({
        role: 'assistant',
        content: err.message || 'The AI advisor could not respond right now. Please try again.',
        timestamp: new Date(),
      });
    } finally {
      setIsTyping(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const autoResize = () => {
    const el = textareaRef.current;
    if (el) {
      el.style.height = 'auto';
      el.style.height = Math.min(el.scrollHeight, 140) + 'px';
    }
  };

  const stageLabel = userType
    ? { class10: 'After Class 10', class12: 'After Class 12', graduate: 'Graduate', graduation: 'Graduate', parent: 'Parent' }[userType]
    : 'Any stage';
  const streamName = context?.stream?.name || context?.field?.label || null;
  const contextLabel = streamName ? `${stageLabel} · ${streamName}` : stageLabel;

  const visiblePrompts = useMemo(() => {
    const prompts = aiAdvisorResponses.prompts;
    if (!userType) return prompts;
    const stream = answers?.stream?.[0];
    if (userType === 'class10') {
      return prompts.filter((p) => !/NEET|engineering college for computer|MBA|IIT/.test(p));
    }
    if (userType === 'class12') {
      if (stream === 'science_pcm') return prompts.filter((p) => !/NEET/.test(p));
      if (stream === 'science_pcb') return prompts.filter((p) => !/engineering|IIT/.test(p));
      if (stream === 'commerce') return prompts.filter((p) => !/engineering|NEET|IIT/.test(p));
      if (stream === 'arts') return prompts.filter((p) => !/engineering|NEET|IIT/.test(p));
    }
    if (userType === 'graduate') {
      return prompts.filter((p) => !/NEET|engineering college for computer/.test(p));
    }
    return prompts;
  }, [userType, answers]);

  return (
    <div className="min-h-screen bg-paper-gradient flex flex-col">
      {/* Header */}
      <div className="bg-white/85 backdrop-blur-xl border-b border-line sticky top-0 z-30">
        <div className="max-w-3xl mx-auto px-5 sm:px-8 py-3.5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <BackLink label="" aria-label="Go back" />
              <Logo size="sm" />
              <div>
                <h1 className="font-ui font-semibold text-ink leading-tight">NAVORA advisor</h1>
                <p className="text-xs text-ink-3 flex items-center gap-1.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 glow-dot" />
                  PERSONALIZED EDUCATION &amp; CAREER GUIDANCE — supporting your assessment
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span className="hidden sm:inline-flex items-center gap-1.5 text-xs text-ink-3 bg-paper border border-line rounded-full px-3 py-1.5">
                <Sparkles className="w-3.5 h-3.5 text-brand-600" />
                {contextLabel} · plain-language guidance
              </span>
              <button
                onClick={startNewChat}
                className="inline-flex items-center gap-1.5 text-xs font-medium text-brand-600 bg-brand-50 hover:bg-brand-100 border border-brand-200 rounded-full px-3 py-1.5 transition-all cursor-pointer"
              >
                <MessageSquarePlus className="w-3.5 h-3.5" />
                New Chat
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Supporting layer explainer */}
      <div className="bg-brand-50/70 border-b border-brand-100">
        <div className="max-w-3xl mx-auto px-5 sm:px-8 py-3.5">
          <p className="text-sm font-medium text-brand-800 leading-relaxed">The conversation doesn&rsquo;t end with your assessment.</p>
          <p className="text-xs text-ink-2 leading-relaxed">The advisor helps you understand your result, ask follow-up questions, compare options, and explore courses and career paths — grounded in your answers.</p>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 w-full">
        <div className="max-w-3xl mx-auto px-5 sm:px-8 py-8">
          <div className="space-y-5">
            <AnimatePresence>
              {chatHistory.map((message, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.25 }}
                  className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  {message.role === 'assistant' && (
                    <span className="mt-1 mr-3 w-8 h-8 rounded-xl bg-brand-950 flex items-center justify-center shrink-0">
                      <Compass className="w-4 h-4 text-cyan-300" />
                    </span>
                  )}
                  <div
                    className={`max-w-[82%] sm:max-w-[75%] px-5 py-3.5 ${
                      message.role === 'user'
                        ? 'bg-brand-500 text-white rounded-2xl rounded-br-md shadow-brand'
                        : 'bg-white border border-line rounded-2xl rounded-bl-md shadow-sm'
                    }`}
                  >
                    <p className={`text-[0.95rem] leading-relaxed ${message.role === 'user' ? 'text-white' : 'text-ink'}`}>
                      {message.content}
                    </p>
                    <p className={`text-[0.68rem] mt-2 ${message.role === 'user' ? 'text-white/50' : 'text-ink-3'}`}>
                      {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </p>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>

            {isTyping && (
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex justify-start"
              >
                <span className="mt-1 mr-3 w-8 h-8 rounded-xl bg-brand-950 flex items-center justify-center shrink-0">
                  <Compass className="w-4 h-4 text-cyan-300" />
                </span>
                <div className="bg-white border border-line rounded-2xl rounded-bl-md shadow-sm px-5 py-4">
                  <div className="flex gap-1.5">
                    {[0, 1, 2].map((i) => (
                      <span
                        key={i}
                        className="w-1.5 h-1.5 rounded-full bg-brand-400"
                        style={{ animation: `typingDot 1.2s infinite ${i * 0.15}s` }}
                      />
                    ))}
                  </div>
                </div>
              </motion.div>
            )}

            <div ref={messagesEndRef} />
          </div>
        </div>
      </div>

      {/* Quick prompts */}
      {chatHistory.length <= 1 && (
        <div className="max-w-3xl mx-auto w-full px-5 sm:px-8 pb-3">
          <p className="eyebrow text-ink-3 mb-3">Try asking about</p>
          <div className="flex flex-wrap gap-2">
            {visiblePrompts.map((prompt, i) => (
              <motion.button
                key={prompt}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 + i * 0.05 }}
                onClick={() => handleSend(prompt)}
                className="px-4 py-2 bg-white border border-line rounded-xl text-sm text-ink-2 hover:border-brand-300 hover:text-ink hover:bg-brand-50/50 transition-all cursor-pointer"
              >
                {prompt}
              </motion.button>
            ))}
          </div>
        </div>
      )}

      {/* Input */}
      <div className="bg-white/85 backdrop-blur-xl border-t border-line sticky bottom-0 z-30">
        <div className="max-w-3xl mx-auto px-5 sm:px-8 py-4">
          <div className="flex items-end gap-2.5">
            <div className="flex-1 relative">
              <textarea
                ref={textareaRef}
                value={input}
                onChange={(e) => { setInput(e.target.value.slice(0, 500)); autoResize(); }}
                onKeyDown={handleKeyDown}
                placeholder="Ask about careers, courses, colleges&hellip;"
                rows={1}
                maxLength={500}
                className="w-full px-5 py-3.5 bg-surface border border-line rounded-2xl text-[0.95rem] text-ink placeholder:text-ink-3 focus:outline-none focus:ring-2 focus:ring-brand-200 focus:border-brand-300 resize-none transition-all leading-relaxed"
              />
            </div>
            <motion.button
              whileHover={{ y: -1 }}
              whileTap={{ scale: 0.95 }}
              onClick={() => handleSend()}
              disabled={!input.trim() || isTyping}
              className="w-11 h-11 bg-brand-500 hover:bg-brand-600 disabled:opacity-40 disabled:cursor-not-allowed rounded-xl flex items-center justify-center text-white transition-all shadow-brand shrink-0"
              aria-label="Send message"
            >
              <ArrowUp className="w-5 h-5" />
            </motion.button>
          </div>
          <p className="text-[0.68rem] text-ink-3 mt-2.5 text-center">
            Guidance for thinking, not a substitute for professional counselling. Always verify major decisions.
          </p>
        </div>
      </div>
    </div>
  );
}